---

- set_fact:
    hardenwebserver_certinfo: '/C=US/ST=CA/L=San Francisco/O=Ansible'
    hardenwebserver_certduration: 1095
## Travis error: "asn1 encoding routines:ASN1_mbstring_ncopy:string too longi:a_mbstr.c:154:maxsize=64" as cn=testing-gce-4d114f77-0ff1-41fb-bd33-22879d3249da.c.eco-emissary-99515.internal
    certificate_cn: "{{ ansible_fqdn }}"

- set_fact:
    certificate_cn: "testing-travis.internal"
    travisci: true
  when: ansible_env['TRAVIS'] is defined and ansible_env['TRAVIS'] == 'true'


- name: apt | self-signed certificate packages dependencies
  apt: name={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - ssl-cert
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Generale SSL self-signed certificate
  command: >
    openssl req -x509 -nodes -sha256 -days {{ hardenwebserver_certduration }} -newkey rsa:2048 
        -subj "{{ hardenwebserver_certinfo }}/CN={{ certificate_cn }}" 
        -keyout {{ ssl_privatedir }}/{{ ansible_fqdn }}.key 
        -out {{ ssl_dir }}/{{ ansible_fqdn }}.crt
        creates={{ ssl_dir }}/{{ ansible_fqdn }}.crt

- name: check private key has good file permissions
  file: "path={{ ssl_privatedir }}/{{ ansible_fqdn }}.key owner=root group={{ ssl_user }} mode=0440"

