---

- block:
    - name: ensure custom directories exist
      file: dest={{ item }} state=directory mode=0755
      with_items:
        - /var/www/welcome
    - name: copy welcome page
      copy:
        src: "{{ jitsi_meet_customized_welcome_filepath }}"
        dest: "/var/www/welcome"
        mode: 0644
        backup: yes
  when: jitsi_meet_customized_welcome


- block:
    - name: ensure custom directories exist
      file: dest={{ item }} state=directory mode=0755
      with_items:
        - /var/www/jitsi-custom
    - name: install customized interface_config.js
      copy: src={{ jitsi_meet_customized_interface_config_filepath }} dest=/var/www/jitsi-custom mode=0644
  when: jitsi_meet_customized_interface_config

