---
- name: Copy Jitsi Meet JS config file.
  template:
    dest: "/etc/jitsi/meet/{{ jitsi_meet_server_name }}-config.js"
    src: jitsi_meet_config.js.j2
    owner: root
    group: root
    mode: "0644"
    backup: yes
  notify: restart jitsi-videobridge

- name: Set jitsi-videobridge log level.
  lineinfile:
    dest: /etc/jitsi/videobridge/logging.properties
    regexp: '^\.level'
    line: ".level={{ jitsi_meet_videobridge_loglevel }}"
    state: present
    backup: yes
  notify: restart jitsi-videobridge
