---

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'
- name: Include version-specific variables for RedHat
  include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: set hostname accorting to jitsi meet, impact multiple paths
## this one fails in container
#  hostname: name={{ jitsi_meet_server_name }}
  command: "hostname {{ jitsi_meet_server_name }}"
## Not possible to set hostname inside unprivileged docker, https://stackoverflow.com/questions/31552455/setting-the-hostname-for-a-container-running-in-kubernetes
  ignore_errors: true
#- debug: var=ansible_fqdn
- name: force to gather facts again to refresh ansible_fqdn
  action: setup
#- debug: var=ansible_fqdn

- include: packages.yml

  # Read Jitsi Meet config files and extract secrets for use in template configs.
  # Import to run these tasks after package installation, but before config tasks.
- include: dynamic_vars.yml

- include: prosody.yml

- include: jitsi_meet.yml

- include: jicofo.yml

- include: nginx.yml

- include: clean_up_default_configs.yml
  when: jitsi_meet_ssl_cert_path != '' and
        jitsi_meet_ssl_key_path != '' and
        jitsi_meet_server_name != 'localhost'

- include: ufw.yml
  when: jitsi_meet_configure_firewall == true

  # Placing the browser extensions last so the associated debugging tasks
  # that display URLs are visible near the end of the play.
- include: browser_extensions.yml
