---
- name: Copy Prosody config template.
  template:
    src: prosody_config.j2
    dest: "/etc/prosody/conf.avail/{{ jitsi_meet_server_name }}.cfg.lua"
    owner: root
    group: root
    mode: "0644"
    # Simply syntax check for validation, doesn't catch config errors.
    validate: "luac -p %s"
    backup: yes
  notify: restart prosody

- name: Symlink Prosody config by domain name.
  file:
    path: "/etc/prosody/conf.d/{{ jitsi_meet_server_name }}.cfg.lua"
    state: link
    src: "/etc/prosody/conf.avail/{{ jitsi_meet_server_name }}.cfg.lua"
  notify: restart prosody

- name: Register jicofo agent with Prosody service.
  command: >
    prosodyctl register focus auth.{{ jitsi_meet_server_name }} {{ jitsi_meet_jicofo_password }}
  args:
    # Yes, prosody actually URL-escapes the directory name for some reason.
    # Must hardcode the escaping in the prefix, since the replace filter only
    # applies to the server name var, not the concatenated string.
    creates: /var/lib/prosody/{{ 'auth%2e'+jitsi_meet_server_name | replace('.', '%2e') }}/accounts/focus.dat
  notify:
    - restart jicofo
    - restart prosody

- name: Generate SSL keypair for Prosody service.
  shell: >
    yes '' | prosodyctl cert generate {{ jitsi_meet_server_name }}
  args:
    creates: /var/lib/prosody/{{ jitsi_meet_server_name }}.crt
  notify:
    - restart jicofo
    - restart prosody
