---
# handlers file for jitsi-meet
- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: restart prosody
  service:
    name: prosody
    state: restarted

- name: restart jicofo
  service:
    name: jicofo
    state: restarted

- name: restart jitsi-videobridge
  service:
    name: jitsi-videobridge
    state: restarted

- name: add public file to www dir to fullfill letsencrypt challenge
  copy:
     dest: "{{ hardenwebserver_rootdir }}/{{ le_challenge['challenge_data'][ certificate_cn ]['http-01']['resource'] }}"
     content: "{{ le_challenge['challenge_data'][ certificate_cn ]['http-01']['resource_value'] }}"